env:
  - GO111MODULE=on

language: go
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go get -t -v ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_API_KEY